name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest


      - name: Install package dependencies
        run: bun install --frozen-lockfile

      - name: Run build script
        run: bun run build
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}


      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: package.json
          push: true
          default_author: github_actions
          message: 'chore: bump version to ${{ github.ref_name }}'

      - name: Update tag
        uses: EndBug/latest-tag@v1
        with:
          ref: ${{ github.ref_name }}


      - name: Publish lib to npm registry
        run: bun publish --access public
        working-directory: lib
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install zip
        run: sudo apt install zip

      - name: Bundle files
        run: |
          mkdir -p ./temp/oxmysql/{web,lib}
          cp ./{LICENSE,README.md,fxmanifest.lua,ui.lua} ./temp/oxmysql
          cp ./lib/MySQL.lua ./temp/oxmysql/lib
          cp -r ./dist ./logger ./temp/oxmysql
          cp -r ./web/build ./temp/oxmysql/web/
          cd ./temp && zip -r ../oxmysql.zip ./oxmysql

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: oxmysql.zip
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
